name: Release Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
          required: true
          default: 'v0.9.2'
          type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'prod'
    strategy:
      matrix:
        cuda_version: ['12.6.3']
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          # all of these default to true to skip
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false
          
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
        with:
          install: true
      
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          if [ "${{ matrix.cuda_version }}" = "12.6.3" ]; then
            cuda_tag="cu126"
          elif [ "${{ matrix.cuda_version }}" = "12.8.1" ]; then
            cuda_tag="cu128"
          else
            echo "Unsupported CUDA version"
            exit 1
          fi
          
          tag=latest-${cuda_tag}  # ${version}
          docker build . -f Dockerfile --target vllm-openai --build-arg max_jobs=2 -t kairos333/vllm:${tag} --no-cache
          docker push kairos333/vllm:${tag}
